services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: mohef
      POSTGRES_PASSWORD: mohef
      POSTGRES_DB: mohef_assessment
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build:
      context: ../apps/backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: mohef
      DB_PASSWORD: mohef
      DB_NAME: mohef_assessment
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
